config/routes.rb
Rails.application.routes.draw do

  root 'pages#index'

  controller :pages do
    get :index
    get :about
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  end
  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<html>
<head>
  <title>BrianshayneRails</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>

</head>
<body>

<%= yield %>

</body>
</html>

app/views/pages/about.html.erb
<div class="grid grid-pad">

  <div class="container col-1-2 mobile-col-1-1">
    <%= link_to root_path , alt: "Home" , class: "block header", id: "info" do %>
      <div class="text_container">
        <div class="text">
          <div class="name">Brian Donohue</div>
          <div class="tagline">Solving things</div>
        </div>
      </div>
      <% end %>
  </div>

  <div class="container-half col-1-2 mobile-col-1-1">
    <%= link_to root_path , alt: "Home" , class: "block", id: "avatar" do %><% end %>
  </div>
</div>


<div class="grid grid-pad no-overflow">
  <div class="arrow bounce">

</div>
  <div class="container-about col-1-1 mobile-col-1-1 ">

    <div class ="about">
      <p>
          Hi, I&rsquo;m Brian.
      </p>
      <p>
          I&rsquo;m originally from <a href="https://goo.gl/maps/zorhXhrVzxj" target="_blank">Marathon Ontario</a>, but have lived all across Canada
      </p>
      <p>
          I started in the Canadian Forces, ended up in radio and now work in software. Who knew?
      </p>
      <p> I somehow have two cats. I currently live in Ottawa, Ontario </p>
      <p>
        Now I work for <a href="https://shopify.com" target="_blank">Shopify</a>, where I concept solutions for <a href="https://shopify.com/plus" target="_blank">Shopify Plus </a> - our high volume / high growth product.
      </p>
      <p>
        <%= link_to "< Back", root_path %>
      </p>
     </p>
  </div>
</div>


</div>
</div>

app/views/pages/index.html.erb
<div class="grid grid-pad">

  <div class="container col-1-2 mobile-col-1-1">
    <%= link_to about_path , alt: "About Me" , class: "block header", id: "info" do %>
          <div class="text_container">
              <div class="text">
                  <div class="name">Brian Donohue</div>
                  <div class="tagline">Solving things</div>
              </div>
          </div>
    <% end %>

  </div>

  <div class="container col-1-2 mobile-col-1-1">
    <%= link_to about_path , alt: "About Me" , class: "block", id: "avatar" do %><% end %>
  </div>
</div>
<div class="grid grid-pad">



  <div class="container col-1-2 mobile-col-1-1">
      <a class="block"
         id="twitter"
         title="Twitter"
         alt="Twitter"
         target="_blank"
         href="https://twitter.com/dianbronohue">
      </a>
  </div>

  <div class="container col-1-2 mobile-col-1-1">
      <a class="block"
         id="github"
         title="GitHub"
         alt="GitHub"
         target="_blank"
         href="https://github.com/brianshayne">
      </a>
  </div>
</div>
<div class="grid grid-pad">

  <div class="container col-1-2 mobile-col-1-1">
      <a class="block"
         id="medium"
         title="Medium"
         alt="Medium"
         target="_blank"
         href="https://medium.com/@briansdonohue/">
      </a>
  </div>

  <div class="container col-1-2 mobile-col-1-1">
      <a class="block"
         id="linkedin"
         title="LinkedIn"
         alt="LinkedIn"
         target="_blank"
         href="https://ca.linkedin.com/in/brian-donohue-a61357114">
      </a>
  </div>
</div>
<div class="grid grid-pad">

  <div class="container col-1-2 mobile-col-1-1">
      <a class="block"
         id="facebook"
         title="Facebook"
         alt="Facebook"
         target="_blank"
         href="https://www.facebook.com/dianbronohue">
      </a>
  </div>

  <div class="container col-1-2 mobile-col-1-1">
      <a class="block"
         id="email"
         title="Email"
         alt="Email"
         target="_blank"
         href="mailto:brianshayne@gmail.com?subject=[briansdonohue.com]">
      </a>
  </div>
</div>